---

################################
# PREFIX
################################

- name: Set 'whisparr_prefix' variable
  ansible.builtin.set_fact:
    whisparr_prefix: 'whisparr'

################################
# DEPENDENCIES
################################

- name: Install prerequisite apt packages
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_apt_packages"))
  ansible.builtin.apt:
    pkg:
      - python3-requests
      - python3-psycopg2
      - python3-lxml
    update_cache: true

- name: Install collection requirements
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: '{{ role_path }}/requirements.yml'

################################
# DOCKER
################################

- name: Apt install docker if required
  when:
    - (lookup("vars", whisparr_prefix + "_toggles_enable_docker_install"))
    - ansible_os_family == 'Debian'
  block:
    - name: Gather apt facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Include docker install tasks
      when: '"docker-ce" not in ansible_facts.packages'
      ansible.builtin.include_tasks: sub_tasks/docker.yml

################################
# CLEAN UP
################################

- name: Register container
  community.docker.docker_container_info:
    name: '{{ lookup("vars", whisparr_prefix + "_basics_name") }}'
  register: whisparr_existing_container_result

- name: Remove existing container
  when: whisparr_existing_container_result.exists
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: '{{ lookup("vars", whisparr_prefix + "_basics_name") }}'
    state: absent
    stop_timeout: 10
  register: whisparr_remove_docker_container
  retries: 5
  delay: 10
  until: whisparr_remove_docker_container is succeeded

################################
# BACKEND NETWORK
################################

- name: Conduct backend network tasks
  block:
    - name: Register backend network
      community.docker.docker_network_info:
        name: '{{ lookup("vars", whisparr_prefix + "_network_backend") }}'
      register: whisparr_network_backend_result

    - name: Network backend builtin fail
      ansible.builtin.fail:
        msg: Backend network does not exist nor is it enabled. Ensure the backend network variables contain valid entries.
      when:
        - not (lookup("vars", whisparr_prefix + "_network_backend_is_enabled"))
        - not whisparr_network_backend_result.exists

    - name: Create backend network
      when:
        - (lookup("vars", whisparr_prefix + "_network_backend_is_enabled"))
        - not whisparr_network_backend_result.exists
      community.docker.docker_network:
        name: '{{ lookup("vars", whisparr_prefix + "_network_backend") }}'
        driver: '{{ lookup("vars", whisparr_prefix + "_network_backend_driver") }}'
        ipam_config:
          - subnet: '{{ lookup("vars", whisparr_prefix + "_network_backend_subnet") }}'

################################
# APPDATA
################################

- name: Create appdata directory
  ansible.builtin.file:
    path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}'
    state: directory
    owner: '{{ lookup("vars", whisparr_prefix + "_env_puid") }}'
    group: '{{ lookup("vars", whisparr_prefix + "_env_pgid") }}'
    mode: '0755'

################################
# CONFIG
################################

- name: Check if config.xml exists
  ansible.builtin.stat:
    path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
  register: whisparr_config_xml

- name: Create config.xml file
  when: not whisparr_config_xml.stat.exists
  block:
    - name: Import config file
      ansible.builtin.template:
        src: '{{ role_path }}/templates/whisparr_config.xml.j2'
        dest: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
        force: true
        owner: '{{ lookup("vars", whisparr_prefix + "_env_puid") }}'
        group: '{{ lookup("vars", whisparr_prefix + "_env_pgid") }}'
        mode: '0664'

    - name: Wait for 'config.xml' to be created
      ansible.builtin.wait_for:
        path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
        state: present

################################
# CONFIG (API)
################################

    - name: Lookup Apikey value
      when: (lookup("vars", whisparr_prefix + "_api_key_is_enabled"))
      community.general.xml:
        path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
        xpath: /Config/ApiKey
        content: text
      register: whisparr_xml_api

    - name: Insert existing api key
      when:
        - (lookup("vars", whisparr_prefix + "_api_key_is_enabled"))
        - (whisparr_xml_api.matches[0].ApiKey is defined) and (whisparr_xml_api.matches[0].ApiKey != lookup("vars", whisparr_prefix + "_api_key"))
      community.general.xml:
        path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
        xpath: /Config/ApiKey
        value: '{{ lookup("vars", whisparr_prefix + "_api_key") }}'

################################
# CONFIG (AUTHELIA)
################################

- name: Change config auth to external if Authelia present
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_external_auth"))
  block:
    - name: Authelia builtin fail
      when: not (lookup("vars", whisparr_prefix + "_authelia_is_enabled"))
      ansible.builtin.fail:
        msg: Authelia is toggled on, but the Authelia container variable is empty.

    - name: Lookup AuthenticationMethod value
      community.general.xml:
        path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
        xpath: /Config/AuthenticationMethod
        content: text
      register: whisparr_xml_external

    - name: Register authelia container
      community.docker.docker_container_info:
        name: '{{ lookup("vars", whisparr_prefix + "_authelia_container_name") }}'
      register: whisparr_authelia_container_result

    - name: Change auth method to external
      when:
        - whisparr_authelia_container_result.exists
        - ((whisparr_xml_external.matches[0].AuthenticationMethod is defined) and (whisparr_xml_external.matches[0].AuthenticationMethod != 'External'))
      community.general.xml:
        path: '{{ lookup("vars", whisparr_prefix + "_paths_location") }}/config.xml'
        xpath: /Config/AuthenticationMethod
        value: External

################################
# POSTGRES
################################

- name: Perform postgres tasks
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_postgres"))
  block:
    - name: Postgres builtin fail
      when: not (lookup("vars", whisparr_prefix + "_postgres_is_enabled"))
      ansible.builtin.fail:
        msg: Postgres is toggled on, but one or more variables are empty.

    - name: Include container tasks
      ansible.builtin.include_tasks: postgres/container.yml

    - name: Include database tasks
      ansible.builtin.include_tasks: postgres/database.yml

    - name: Include config.xml tasks
      ansible.builtin.include_tasks: postgres/config_xml.yml

################################
# TRAEFIK
################################

- name: Conduct traefik tasks
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_traefik"))
  block:
    - name: Traefik builtin fail
      when: not (lookup("vars", whisparr_prefix + "_traefik_is_enabled"))
      ansible.builtin.fail:
        msg: Traefik is toggled on, but the domain varible is empty.

    - name: Register traefik network
      community.docker.docker_network_info:
        name: '{{ lookup("vars", whisparr_prefix + "_traefik_network") }}'
      register: whisparr_traefik_network_result

    - name: Traefik builtin fail
      when:
        - not (lookup("vars", whisparr_prefix + "_traefik_network_is_enabled"))
        - not whisparr_traefik_network_result.exists
      ansible.builtin.fail:
        msg: Traefik network does not exist nor is it enabled. Ensure the Traefik network variables contain valid entries.

    - name: Create traefik network
      when: not whisparr_traefik_network_result.exists
      community.docker.docker_network:
        name: '{{ lookup("vars", whisparr_prefix + "_traefik_network") }}'
        driver: '{{ lookup("vars", whisparr_prefix + "_traefik_network_driver") }}'
        ipam_config:
          - subnet: '{{ lookup("vars", whisparr_prefix + "_traefik_network_subnet") }}'

################################
# CLOUDFLARE
################################

- name: Perform Cloudflare DNS tasks
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_cloudflare_dns"))
  block:
    - name: Cloudflare builtin fail
      when: not (lookup("vars", whisparr_prefix + "_cloudflare_is_enabled"))
      ansible.builtin.fail:
        msg: Cloudflare DNS is toggled on, but the cloudflare API token variable is empty.

    - name: Include cloudflare tasks
      ansible.builtin.include_tasks: sub_tasks/cloudflare.yml

################################
# NFS
################################

- name: Include nfs tasks
  ansible.builtin.include_tasks: sub_tasks/nfs.yml

################################
# RCLONE
################################

- name: Perform rclone tasks
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_rclone"))
  block:
    - name: Rclone builtin fail
      when: not (lookup("vars", whisparr_prefix + "_rclone_volume_is_enabled"))
      ansible.builtin.fail:
        msg: Rclone is toggled on, but one or more volume variables are empty.

    - name: Include rclone tasks
      ansible.builtin.include_tasks: sub_tasks/rclone.yml

################################
# THEMEPARK
################################

- name: Run themepark tasks
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_themepark_local"))
  block:
    - name: Register themepark container
      community.docker.docker_container_info:
        name: '{{ lookup("vars", whisparr_prefix + "_themepark_basics_name") }}'
      register: whisparr_themepark_container_result

    - name: Include themepark tasks
      when: not whisparr_themepark_container_result.exists
      ansible.builtin.include_tasks: sub_tasks/themepark.yml

################################
# CONTAINER
################################

- name: Create container
  when: not (lookup("vars", whisparr_prefix + "_toggles_enable_traefik"))
  community.docker.docker_container:
    name: '{{ lookup("vars", whisparr_prefix + "_basics_name") }}'
    image: '{{ lookup("vars", whisparr_prefix + "_basics_image_repo") }}:{{ lookup("vars", whisparr_prefix + "_basics_image_tag") }}'
    networks: '{{ lookup("vars", whisparr_prefix + "_networks") }}'
    env: '{{ lookup("vars", whisparr_prefix + "_envs") }}'
    ports:
      - '{{ lookup("vars", whisparr_prefix + "_ports_host") }}:{{ lookup("vars", whisparr_prefix + "_ports_cont") }}'
    volumes: '{{ lookup("vars", whisparr_prefix + "_volumes") }}'
    restart_policy: '{{ lookup("vars", whisparr_prefix + "_basics_restart_policy") }}'

- name: Create traefik container
  when: (lookup("vars", whisparr_prefix + "_toggles_enable_traefik"))
  community.docker.docker_container:
    name: '{{ lookup("vars", whisparr_prefix + "_basics_name") }}'
    image: '{{ lookup("vars", whisparr_prefix + "_basics_image_repo") }}:{{ lookup("vars", whisparr_prefix + "_basics_image_tag") }}'
    networks: '{{ lookup("vars", whisparr_prefix + "_networks") }}'
    env: '{{ lookup("vars", whisparr_prefix + "_envs") }}'
    labels: '{{ lookup("vars", whisparr_prefix + "_labels") }}'
    ports:
      - '{{ lookup("vars", whisparr_prefix + "_ports_host") }}:{{ lookup("vars", whisparr_prefix + "_ports_cont") }}'
    volumes: '{{ lookup("vars", whisparr_prefix + "_volumes") }}'
    restart_policy: '{{ lookup("vars", whisparr_prefix + "_basics_restart_policy") }}'
