---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ whisparr_cloudflare_api_token }}'
    zone: '{{ whisparr_cloudflare_zone }}'
    state: absent
    type: CNAME
    record: '{{ whisparr_cloudflare_record }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ whisparr_cloudflare_api_token }}'
    zone: '{{ whisparr_cloudflare_zone }}'
    state: absent
    type: A
    record: '{{ whisparr_cloudflare_record }}'

- name: Get public ip for DNS tasks
  block:
    - name: Get public IP
      community.general.ipify_facts:
        timeout: 20
      delegate_to: localhost
      register: public_ip

    - name: Public IP output
      ansible.builtin.debug:
        msg: '{{ ipify_public_ip }}'

- name: Add whisparr DNS record
  community.general.cloudflare_dns:
    api_token: '{{ whisparr_cloudflare_api_token }}'
    zone: '{{ whisparr_cloudflare_zone }}'
    state: present
    solo: true
    proxied: '{{ whisparr_cloudflare_proxy }}'
    type: '{{ whisparr_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ whisparr_cloudflare_record }}'
  register: whisparr_cloudflare_record_creation_status

- name: Tasks on success
  when: whisparr_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        whisparr_cloudflare_record_print: '{{ (whisparr_cloudflare_record == whisparr_cloudflare_zone) | ternary(whisparr_cloudflare_zone, whisparr_cloudflare_record + "." + whisparr_cloudflare_zone) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ whisparr_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ whisparr_cloudflare_proxy }}'
